;METADATA=(Diff=true, UseCommands=true)
[/Script/GameplayTags.GameplayTagsSettings]
ImportTagsFromConfig=True
WarnOnInvalidTags=True
ClearInvalidTags=False
AllowEditorTagUnloading=True
AllowGameTagUnloading=False
FastReplication=False
bDynamicReplication=False
InvalidTagCharacters="\"\',"
NumBitsForContainerSize=6
NetIndexFirstBitSegment=16
+GameplayTagList=(Tag="Hologram",DevComment="")
+GameplayTagList=(Tag="Hologram.Box",DevComment="")
+GameplayTagList=(Tag="Hologram.Chair",DevComment="")
+GameplayTagList=(Tag="Hologram.Corpse",DevComment="")
+GameplayTagList=(Tag="Hologram.FuelCell",DevComment="")
+GameplayTagList=(Tag="Hologram.Green",DevComment="")
+GameplayTagList=(Tag="Hologram.Microscope",DevComment="")
+GameplayTagList=(Tag="Hologram.Pink",DevComment="")
+GameplayTagList=(Tag="Hologram.PlanetModel",DevComment="")
+GameplayTagList=(Tag="Hologram.Plant",DevComment="")
+GameplayTagList=(Tag="Hologram.Scattered",DevComment="")
+GameplayTagList=(Tag="Hologram.Storage",DevComment="")
+GameplayTagList=(Tag="Hologram.WallPlant",DevComment="")
+GameplayTagList=(Tag="SpawnGroup",DevComment="Scattered")
+GameplayTagList=(Tag="SpawnGroup.All",DevComment="Group All Objects")
+GameplayTagList=(Tag="SpawnGroup.Corpse",DevComment="")
+GameplayTagList=(Tag="SpawnGroup.EditorTest",DevComment="EditorTest")
+GameplayTagList=(Tag="SpawnGroup.FuelCell",DevComment="")
+GameplayTagList=(Tag="SpawnGroup.Plant",DevComment="")
+GameplayTagList=(Tag="SpawnGroup.Scattered",DevComment="")
+GameplayTagList=(Tag="SpawnGroup.Trash",DevComment="")

